### ISSUE TITLE
Crypto packages not found by exe

### ISSUE THREAD

**Issue by jboss38** [py2exe/py2exe#105]
Hello,

I'm trying to do one ".exe" file that contains Crypto.

I was able to do it with "'packages': ['Crypto']" option.
I checked all the crypto files (.pyd) are include in the .exe
But the exe is still looking for the path folder next to the .exe

How can I fix that ?

TLDR : including packages not working since .exe still looking for the folder wth lib.

**Comment by albertosottile** [comment]
I am not sure I understand your issue, but `Crypto` should be supported by py2exe, as there is a hook that copies the library needed for you https://github.com/py2exe/py2exe/blob/1071a13835d9aa9874d5868a2763366479869307/py2exe/hooks.py#L592. 

You can give a look at a "reference" implementation in the test case here https://github.com/py2exe/py2exe/tree/master/tests/functional/pycryptodome_test

For the moment, I am closing this since this case is covered by the CI. Please feel free to reopen it in case you still encounter this error with the proposed implementation.
