### ISSUE TITLE
py2exe executable cannot be digitally signed with the option zipfile=None

### ISSUE THREAD

**Issue by urishab** [py2exe/py2exe#131]
With zipfile=None, py2exe bundles all the code inside the built executable.
Problem is, once that executable is digitally signed it no longer works and py2exe bootloader fails to load files from the included package.

Reading through PyInstaller documentation they seem to have encountered the same issue and are using a "magic string" to locate the bundled package inside the executable.
[See here for details.](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Code-Signing)

I'm guessing that py2exe is using the end of the file to look for the package, even though I couldn't find where it's doing that in the code. I'd be happy if someone could direct me the code that does that.

Signing the built executable should be supported in py2exe especially because unsigned executables are becoming less and less accepted. 
See this closed issue #73 for details about detecting py2exe as a false positive virus / malware. 
Signed executable raise fewer alarms.

**Comment by albertosottile** [comment]
As I am sure you know, there is no support provided for the `zipfile = None` option, which is not documented and it is simply provided as-is. Supporting this option actively requires a lot of constant tweaks to the codebase, and I do not have the capacity for that. 

A quick question for you would be: does signing work when `zipfile = None` is not used? My primary concern is that `py2exe` works when signing "regular" executables, at least. 

Once again, even though I do not intend to actively support `zipfile = None` anymore, a PR that addresses this issue is more than welcome.

**Comment by urishab** [comment]
Hi Alberto

Actually, I didn't know you didn't intend on supporting zipfile=None
I always use this option and it works flawlessly for me across versions of Python (3.6-3.9)

Can you give me some pointers about the part of the code that supports this option?

And do you mean that you did a lot of tweaks to support that and don't intend to continue or that you expect this to require work in the future?

**Comment by albertosottile** [comment]
> Hi Alberto
> 
> Actually, I didn't know you didn't intend on supporting zipfile=None I always use this option and it works flawlessly for me across versions of Python (3.6-3.9)

I am glad to hear that. Existing users were the reason why I did not remove the feature outright.

> And do you mean that you did a lot of tweaks to support that and don't intend to continue or that you expect this to require work in the future?

I remember working a lot on this in the early releases of the fork and then having to stop because I could not allocate enough capacity to it.

> Can you give me some pointers about the part of the code that supports this option?

The majority of the feature is implemented in https://github.com/py2exe/py2exe/blob/master/py2exe/runtime.py, look for the areas compatible with `bundle_files==0`, e.g. https://github.com/py2exe/py2exe/blob/b183301a2dec8a4e2c8eb72df1acac3934b8ec7b/py2exe/runtime.py#L605 

There is a C part of course, but you can treat that as an independent Python dependency (`zipextimporter`) that just automatically loads the Python modules and packages from the bundled zip or exe file.

**Comment by urishab** [comment]
Thanks!
I think there's some confusion here as bundle_files is different than zipfile=None
bundle_files determines which files go inside the bundle rather that be included in the dist folder.
That lib file is a normal ZIP files unless you specify zipfile=None in which case the zipfile is just appended at the end of the EXE file.

If you combine bundle_files=1 and zipfile=None you can create a single file EXE that just runs - kind of like the setup you can download. 
This is a pretty cool option.

Anyway I'll try to look into that and see if I have some more insights and maybe we can keep it alive.

**Comment by albertosottile** [comment]
> I think there's some confusion here as bundle_files is different than zipfile=None bundle_files determines which files go inside the bundle rather that be included in the dist folder. That lib file is a normal ZIP files unless you specify zipfile=None in which case the zipfile is just appended at the end of the EXE file.

I am aware of this, but a lot of the code that creates the zip file (which gets appended to the exe file when `zipfile=None`) is different depending on the level of `bundle_files` and AFAIK this has some influence in the way the single bundled file is created.

**Comment by urishab** [comment]
Going back to this issue I retested with python 3.9, py2exe 0.11.1.1
This now seems to work!
Not sure what specifically made the difference but for me this is solved now.
