### ISSUE TITLE
ignores option is ignored/ still supported

### ISSUE THREAD

**Issue by jmoreton** [py2exe/py2exe#140]
Is the `ignores` option still supported? as it doesn't seem to do anything and I can't see where this is passed to the module finder.
It looks like its missing from being passed to the `Scanner` in `runtime.py`.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. It looks like the option was never implemented for Python 3 (I went back to https://github.com/py2exe/py2exe/commit/bc4c86f49ee22ed35b4878563c638cb79d2788ba and could not find it). When I updated `ModuleFinder` for Python 3.10, I added the necessary adjustments that were in the older versions (`mf34` and `mf3`), but did not realize that indeed this option was never passed to it. 

Since the option has not worked for at least 8 years and this is the first time someone is reporting this, I would rather delete it from the code base than reimplement it.  I will do this in the next release.

**Comment by albertosottile** [comment]
Fixed in 0.12.0.0
