### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect.

### ISSUE THREAD

**Issue by youmustp** [py2exe/py2exe#187]
INFO:runtime:Analyzing the code
INFO:runtime:Found 440 modules, 12 are missing, 0 may be missing

  12 missing Modules
  ------------------
?__ __main____                            imported from bdb, pdb
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg                             imported from platform
? asyncio.DefaultEventLoopPolicy      imported from -
? dummy.Process                       imported from multiprocessing.pool
? java.lang                           imported from platform
? org.python.core                     imported from copy, pickle
? os.path                             imported from os, pkgutil, py_compile, sysconfig, tracemalloc, unittest, unittest.util      
? readline                            imported from cmd, code, pdb
? test                                imported from multiprocessing.util
Building 'dist\main.exe'.
Traceback (most recent call last):
  File "c:\Users\youmu\Downloads\mathers for mon(ey)s\freeze.py", line 4, in <module>
    freeze(console=['main.py'])
  File "C:\Users\youmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\py2exe\__init__.py", line 191, in freeze
    builder.build()
  File "C:\Users\youmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\py2exe\runtime.py", line 246, in build
    self.build_exe(target, exe_path, options.libname)
  File "C:\Users\youmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\py2exe\runtime.py", line 353, in build_exe
    resource.add(type="PYTHONSCRIPT", name=1, value=script_info)
  File "C:\Users\youmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\py2exe\resources.py", line 49, in add
    raise WindowsError(details) from None
OSError: [WinError 87] The parameter is incorrect.

**Comment by sdxsd** [comment]
I had this error and what seemingly caused it was that I installed Python from the Microsoft Store rather than from python.org.
Try reinstalling, might work.

**Comment by albertosottile** [comment]
I second the comment from @sdxsd, please uninstall Python and reinstall from www.python.org

**Comment by hayashibob** [comment]
**Root cause identified and resolved!**

If you are using **Microsoft Store Python** (or virtual environments created from it), `kernel32.BeginUpdateResourceW` fails with `ERROR_FILE_NOT_FOUND (2)` when passed a **relative path** like `dist\app.exe`. This is because MSIX packaged Python resolves relative paths for some Win32 APIs against the package installation folder rather than the current working directory.

Because `py2exe`'s `resources.py` does not check if `BeginUpdateResourceW` returns a `NULL` handle, it passes `NULL` directly to `UpdateResourceW`, which triggers `[WinError 87] The parameter is incorrect` as a secondary error.

### Workaround (Add to your `setup.py`):
```python
import os
import py2exe._wapi as _wapi

_orig_BeginUpdateResourceW = _wapi.BeginUpdateResourceW
def _fixed_BeginUpdateResourceW(filename, delete_existing):
    return _orig_BeginUpdateResourceW(os.path.abspath(filename), delete_existing)
_wapi.BeginUpdateResourceW = _fixed_BeginUpdateResourceW
```

Detailed 7-phase investigation report and technical breakdown:
https://mcsm.jp/documents/msstore_python_py2exe_winerror87_investigation/
