### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by leonardder** [py2exe/py2exe#49]
I think this is the only serious fork of Py2exe that's getting recent attention. Have you considered trying to claim the py2ee project on PyPI so we can get it from there as well?

**Comment by albertosottile** [comment]
I contemplated the idea, but claiming an abandoned project name is quite difficult... the best approach would be to contact the former owners. 

In the end, I did not proceed further because I am the only maintainer of this fork and I do not really have a lot of time to dedicate to it. I would be sad for taking the name on pypi and then soon be forced to abandon it.

So,’ my idea was to wait until the fork got a little more traction, before starting the claiming procedure.

**Comment by albertosottile** [comment]
You might have noticed some movements around here, as I decided to stop contemplating and start acting.

First, the new home of this project is https://github.com/py2exe/py2exe (thanks to the former owner of the `py2exe` username who gently granted me permission to use it). GitHub should redirect the old URL indefinitely but, in any case, I would encourage everyone to update their links accordingly.

Second, the CI/CD wheels are now deployed on a new, dedicated, Bintray space available here: https://bintray.com/py2exe/py2exe/py2exe. Users and interested contributors will find the latest builds there, which will include pre-release fixes and new features from development branches. If you were downloading binaries from the former Bintray repository, I would encourage you, once again, to update your URLs.

Last, but definitely not least, from today the latest wheels of `py2exe` are available on PyPI (https://pypi.org/project/py2exe/), which now becomes the official distribution channel for this repository! New releases will be uploaded to the index as soon as they are finalized. Many thanks to @theller, @jretz, and @mhammond for making all this possible (and for having developed this great tool in the first place).

I sincerely hope that all these changes will help in giving more visibility to this project. As always, all contributions are always encouraged.

@leonardder @Athanasius @et0h I believe this news closes this issue. Good luck in developing your future projects with `py2exe`.
