### ISSUE TITLE
Error upon installing py2exe

### ISSUE THREAD

**Issue by Qutadah** [py2exe/py2exe#56]
Hello,

I am recieving the following error by running the command  pip install py2exe.

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I am using google colab, any idea how I can solve this problem?

Thanks

**Comment by albertosottile** [comment]
Hello, thanks for reporting this. 

Personally, I have never used Google Colab but I think the underlying issue is that their VMs are running Linux, whereas `py2exe` requires Windows to be used. You can quickly check this by running
```
import sys
sys.platform
```
in one of your notebooks. 

Perhaps I should change the code in `setup.py` to throw a more meaningful error or strip the `sdist` distribution entirely, forcing the use of prebuilt wheels (as `pywin32` does, which would throw `ERROR: No matching distribution found for ...`). I will leave this issue open and think about it.

**Comment by Qutadah** [comment]
Hello, 

thanks for the reply, yes you are right, they are using linux, i checked it...  can you recommend any other module that would work with google colab?

Thanks for your help.

**Comment by albertosottile** [comment]
That really depends on your needs... In general, PyInstaller and cx_freeze are the main alternatives for Linux freezing and packaging.

**Comment by Qutadah** [comment]
ok great, thanks alot! appreciated 👍🏼
