### ISSUE TITLE
Option "skip_archive" does not work anymore

### ISSUE THREAD

**Issue by hppi-johnsson** [py2exe/py2exe#81]
skip_archive does not work anymore. There is some commented out code in distutils_buildexe.py where the string can be found.

I use this option a lot to create a redistributable where .py files can be edited right in the lib folder. Great for debugging at a target computer.

**Comment by albertosottile** [comment]
Hi, 

thanks for reporting this. I am afraid the `skip_archive` option was removed on purpose. The reason is that `py2exe` is quite an extensive project and I do not have a lot of time for maintaining it. So, over time I am trying to strip away some non-critical features with the goal of ending up with a slimmer package, eventually. 

For your use case, I would suggest to pack your code in a zip file together with a virtual environment that contains all the dependencies. You could then just uncompress the zip file in the target computer and work with your Python files as before.

**Comment by hppi-johnsson** [comment]
Thanks for your efforts and the good shape of the package. It works great!

I am thinking about tweaking the library myself. Any hint in which file/line the ZIP is created?

Would it be an option to simply unpack the zip file and add something to the path?

**Comment by albertosottile** [comment]
The archive is created in here
https://github.com/py2exe/py2exe/blob/b8b9cf60d1ac3f243e09330b29a6bc7de419929b/py2exe/runtime.py#L385-L387

and the relevant `PYTHONPATH` is included in the exe here 
https://github.com/py2exe/py2exe/blob/b8b9cf60d1ac3f243e09330b29a6bc7de419929b/py2exe/runtime.py#L336-L345

You would also have to patch the code in `build_archive` to not compile the scripts, otherwise you would still get uneditable `.pyc` files.

An alternative could be to go back in time to when the feature was still functional (I think in Python 2 on Sourceforge, but I am not sure) and look there how the feature was implemented. Or to look at the commented code in `distutils_buildexe` that you mentioned before.

For now, I am closing this issue for the reasons mentioned before. Good luck with your effort. If for any reason this does not work, please consider the alternative of shipping a virtual environment.
