### ISSUE TITLE
This seems to be a trojan?

### ISSUE THREAD

**Issue by abhra2020-smart** [py2exe/py2exe#86]
This package uses a file called run-pyx.y-win-whateveryourcpuisbasedon (where x and y is python's major version and y it's minor version. whateveryourcpuisbasedon is well, what your cpu is based on) and according to McAfee, it's a virus?

**Comment by albertosottile** [comment]
Thanks for reporting this. `py2exe` binaries are not signed (due to the lack of a paid signing certificate) and they are not widespread so, some antivirus software tend to flag them as "harmful". However, if you look at the detected thread class, it should be rather vague, showing that no clear harmful code was indeed identified (e.g. Generic, GEN, ...).

Nevertheless, the only guarantee that the software contains no threats is in the public availability of the source code and of the transparent/public chain that builds the wheels, which are both hosted here on GitHub. If you want, you can also submit the binary to your antivirus provider (in your case, McAfee) for further inspection and, I am sure, clearing.

At the moment, there is no plan to sign binaries, as this would significantly complicate the build phase and it would also introduce a fixed expense to be paid. Further information on this false detection and on the possible mitigation actions can be found [in this comment](https://github.com/py2exe/py2exe/pull/75#issuecomment-797086529).
