### ISSUE TITLE
Kivy App will not run, ImportError:

### ISSUE THREAD

**Issue by tsmorton60** [py2exe/py2exe#90]
A py2exe compiled minimal Kivy app will not run. It gives an import error,

ImportError: (No module named 'kivy.weakmethod') 'C:\\Users\\tim\\Code\\kivy-app\\compiled\\kivy._clock.pyd'

Yet this file is found in the folder where py2exe places its files.

Attached is the .py file that I used. (You must have kivy installed.) 

[paint.zip](https://github.com/py2exe/py2exe/files/6633110/paint.zip)

**Comment by ksvintsov** [comment]
https://github.com/py2exe/py2exe/pull/103 probably fixes this.

**Comment by albertosottile** [comment]
@tsmorton60 The error message you reported means that the file listed in the error (`kivy._clock.pyd`) is trying to import a module (`kivy.weakmethod`) and the interpreter is not able to find it. Hence, it is expected the file mentioned there exists and is in the right path. What you should look for is why the missing module is not the distributed package.

Most likely, since Kivy is a complex Python package, a custom hook would be required to use it correctly in `py2exe`. As a workaround, you could try to add `kivy` in the `packages` dictionary in your `setup.py` script. However, there is no guarantee this will work.

@ksvintsov I do not think #103 is related to this, as the missing module is not in the file reported in the error.

**Comment by albertosottile** [comment]
This is one of the cases in which a single hook cannot do the job. For Kivy, as well for other GUI bindings such as PyQt5 and PySide2, `py2exe` would need a set of API for e.g. importing the right styles, plugins, and (perhaps) needed submodules. A simple hook cannot be coded to do this and still be customizable by the user.

Alas, at the moment I do not have the time to write all this code, so `py2exe` lacks serious support for these bindings (as mentioned in the Known Issues https://github.com/py2exe/py2exe#known-issues).

Nevertheless, I took the time to look at your example code and wrote a `setup.py` script suitable for it:
```python
from distutils.core import setup
import py2exe

def hook_kivy(finder, module):
    import glob
    import os.path

    # copy data files
    import kivy
    kivy_dir = os.path.join(os.path.dirname(kivy.__file__), 'data')
    assert os.path.isdir(kivy_dir)
    finder.add_datadirectory("kivy/data", kivy_dir, recursive=True)

    # copy binary dependencies
    from kivy_deps import sdl2
    for dll_path in glob.glob(os.path.join(sdl2.dep_bins[0], '*.dll')):
        finder.add_dll(dll_path)

    # add environment variables that point to the copied paths at runtime
    finder.add_bootcode("""
def kivy_env_paths():
    import os
    import sys
    basepath = os.path.dirname(sys.executable)
    kivy_data_dir = os.path.join(basepath, 'kivy', 'data')
    os.environ["KIVY_DATA_DIR"] = kivy_data_dir
    os.environ["KIVY_NO_CONSOLELOG"] = "1"

kivy_env_paths()
del kivy_env_paths
""")

py2exe.hooks.hook_kivy = hook_kivy

setup(
    windows = [{"script": "paint.py"}],
    options={"py2exe": {"packages": ['kivy', 'kivy_deps']}},
    )
```

I am able to run the executable packed with this script without installing Kivy on my test machine. Side note: the packed folder is about 30 MB, not good but also not especially bad for a GUI Python app. Feel free to take this script and adapt it for your actual Kivy app. 

I hope this helps but for the moment I am closing this issue, as a proper interface to handle Kivy and similar other packages properly will not come soon.
